### PR TITLE
Makefile: remove config.h when cleaning, and change DESTDIR to PREFIX

### PR DESCRIPTION
**Pull request by dawidd6**
I think it's good to remove also config.h when doing `make clean` to achieve clean git repository

Also i've changed DESTDIR to PREFIX and added mkdirs to create directories, it's useful for packaging.

### CODE REVIEW

**Comment by deadpixi** [comment]
I don't know that we should remove `config.h` on `make clean`, as it might blow away a user's customizations. Maybe we should make a `clean-all` target or something? We definitely should change `DESTDIR` to `PREFIX` though.

**Comment by Mazeto** [comment]
There's no need to delete config.h, just put "config.h" on ".gitignore".

**Comment by 0mp** [comment]
I think that we should not delete config.h during clean target. 

This is the behavior people use in software like [dwm](https://git.suckless.org/dwm/tree/Makefile), [quark](https://git.suckless.org/quark/tree/Makefile) or [st](https://git.suckless.org/st/tree/Makefile), which use config.def.h mechanism.

**Comment by 0mp** [comment]
Also, while here, it would be nice to be able to modify the manual path as well. The standard path for section 1 manual pages is `/usr/local/man/man1/` (no `share`). 

Can we introduce something like `MANPATH`?

**Comment by deadpixi** [comment]
This is mostly fixed in master now, I believe.

**Comment by hmontone** [comment]
> This is mostly fixed in master now, I believe.

Is there some reason why `DESTDIR` was not changed to `PREFIX` in the end? As far as I understand, `PREFIX` is traditionally used for what `DESTDIR` does here, and on the other hand `DESTDIR` typically has completely different meaning.

**Pull request closed without merging**
